# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.22
_src_path: https://github.com/oca/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Akretion
org_slug: akretion
rebel_module_groups:
- sale_configurator_pricelist_tax
repo_description: Sale configurator
repo_name: Sale Configurator
repo_slug: sale-configurator
repo_website: https://github.com/akretion/sale-configurator
use_pyproject_toml: false
use_ruff: false

